### ISSUE TITLE
La licence MIT est inadaptée à des icônes

### ISSUE THREAD

**Issue by DavidBruant** [datalocale/pictoGironde#1]
La licence MIT s'applique plutôt à du logiciel.
Les travaux graphiques se distribuent plutôt sous licence [Creative Commons](https://creativecommons.org/licenses/). 

La licence CC la plus proche de la licence MIT dans l'esprit est la licence [CC-BY](https://creativecommons.org/licenses/by/4.0/).

**Comment by datalocale** [comment]
Je suis au courant. Il ne me semble pas que github propose de licence de type cc

**Comment by DavidBruant** [comment]
> Il ne me semble pas que github propose de licence de type cc

C'est l'auteur de repo qui choisit la licence de son travail en toute liberté. 
Github fournit des licences utilisées habituellement pour rendre le process plus rapide quand on veut choisir l'une de ces licences, mais rien n'y oblige.

On peut [ajouter une licence](https://help.github.com/articles/adding-a-license-to-a-repository/). Les étapes 4-6 sont optionnelles, on peut copier/coller n'importe quel texte légal de licence.

Il est d'usage sans que ça soit obligatoire que le readme rappelle la licence utilisée par une appellation courte.
